// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_D1_DATABASE_ID: string;
	CLOUDFLARE_TOKEN: string;
	OP_SCRAPER_DB: D1Database;
	PIRATEGPT_CHAT_DB: D1Database;
	ONE_PIECE_VECTORS: VectorizeIndex;
	AI: Ai;
	RAG_WORKFLOW: Workflow;
}
