// Generated by Wrangler by running `wrangler types`

interface Env {
	CLOUDFLARE_ACCOUNT_ID: string;
	CLOUDFLARE_D1_DATABASE_ID: string;
	CLOUDFLARE_TOKEN: string;
	MY_DURABLE_OBJECT: DurableObjectNamespace /* MyDurableObject */;
	DB: D1Database;
	ONE_PIECE_VECTORS: VectorizeIndex;
	AI: Ai;
}
